/* tslint:disable */
/* eslint-disable */
/**
 * Национална Здравно-информационна Система
 * Услуги за интеграция с **НЗИС**. Тези услуги предоставят възможност на специализирания медицински и аптечен софтуер да обменя информация с Националната Здравно-информационна система.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";

